NUMBER_OF_REGISTERS = 4
MEMORY_SIZE = 200

IP_INDEX = 0
SP_INDEX = 1

COMMAND_READ = 0
COMMAND_PUTSTR = 1
COMMAND_EXIT = 2
COMMAND_PUSH = 3
COMMAND_POP = 4
COMMAND_CALL = 5
COMMAND_FUNCB = 6
COMMAND_FUNCE = 7
COMMAND_MOV = 8
COMMAND_ADD = 9
COMMAND_SUB = 10
COMMAND_GOTO = 11
COMMAND_PRINT = 12
