NUMBER_OF_REGISTERS = 8
MEMORY_SIZE = 400

IP_INDEX = 0
SP_INDEX = 1

IP_OFFSET = 5

COMMAND_ADD = 0
COMMAND_CALL = 1
COMMAND_EXIT = 2
COMMAND_FUNCB = 3
COMMAND_FUNCE = 4
COMMAND_GOTO = 5
COMMAND_MOV = 6
COMMAND_POP = 7
COMMAND_PRINT = 8
COMMAND_PUSH = 9
COMMAND_PUTSTR = 10
COMMAND_READ = 11
COMMAND_SUB = 12

DESCRIPTION = 'This program calculates the n-th number in fibonacci sequence [1, 1, 2, 3, 5, 8, ...].'
ENTER = 'Enter a number:'
