# Generated by Django 2.0.2 on 2018-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe your task here', max_length=256)),
                ('additional_info', models.TextField(help_text='Write some tips here', max_length=1024)),
            ],
        ),
    ]
